### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by eloo** [daneharrigan/hipchat#22]
Hi,
i'm trying to use your library to connect to a self hosted hipchat instance and facing a problem with the TLS connection.
I'm everytime getting the following error:
```client error: x509: certificate has expired or is not yet valid```
So it seems that the certificate is expired but I want to connect anyway. So how can I disable the Cert verify?
Thanks

**Comment by daneharrigan** [comment]
Hey @Eloo! I think you can achieve what you're looking for pretty easily.

In [xmpp.go:83](https://github.com/daneharrigan/hipchat/blob/master/xmpp/xmpp.go#L83), you see I'm passing in a `tls.Config` into my `tls.Client`. The `tls.Config` has an option called [InsecureSkipVerify](https://golang.org/pkg/crypto/tls/#Config.InsecureSkipVerify) to skip cert verification.

I don't expose a way to configure this, but I'm more than happy to merge a PR that does. What do you think about exposing a method like `xmpp.UseTLSWithConfig(host string, config *tls.Config)`?

**Comment by Eloo** [comment]
Okay, will try to provide a PR in time.
