### ISSUE TITLE
Receiving unsolicited xmpp.NsDisco or xmpp.NsIqRoster will block listen function

### ISSUE THREAD

**Issue by fedyakin** [daneharrigan/hipchat#8]
This problem can be reproduced by connecting to hipchat and changing the name of a user.

The receivedRooms and receivedUsers channels are unbuffered, so sending data to this channel will block until something receives from this channel.  The only time these channels are received from are in the Users() and Rooms() methods.  

However, these messages generate a request so would still leave the listen thread blocked.  We exposed the channels and used a goroutine similar to this to avoid the endless block.  Note: `Rooms()` and `Users()` in this example just return the channels and don't make requests (the same as `Messages()`).
```go
go func() {
	for {
		select {
		case message := <-client.Messages():
			log.Printf("Received message: %v", message)
		case rooms := <-client.Rooms():
			log.Printf("Received rooms: %v", rooms)
		case users := <-client.Users():
			log.Printf("Received users: %v", users)
		}
	}
}()
```
Obviously there still needs to be work done to communicate received rooms and users to other goroutines, but this is one way to avoid the problem.

**Comment by daneharrigan** [comment]
@fedyakin would you be able to put together a PR? I'd be more than happy to help walk through it with you

**Comment by daneharrigan** [comment]
closing with 9b8743b68827e88faa248bc432197c570871117d merged
